name: panda_technician
description: A new Flutter project.

publish_to: "none"


version: 1.0.9+9

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.1
  image_cropper: ^4.0.1
  intl_phone_field: ^3.1.0
  geolocator: ^9.0.2
  file_picker: ^5.2.4
  date_time_picker: ^2.1.0

  tutorial_coach_mark: ^1.2.4
  empty_widget: ^0.0.5
  amazon_cognito_identity_dart_2: ^3.1.1
  flutter_local_notifications: ^15.1.0+1
  webview_flutter_android: ^3.3.1
  webview_flutter_wkwebview: ^3.1.1

  http: ^0.13.4
  image_picker: ^1.0.1 
  firebase_messaging: ^14.2.0
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.5
  google_maps_webservice: ^0.0.20-nullsafety.5
  flutter_lints: ^2.0.0
  table_calendar: ^3.0.8  
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  flutter_countdown_timer: ^4.1.0
  url_launcher: ^6.0.0
  image: ^4.0.17

  latlng: ^0.2.0
  flutter_map: ^4.0.0 
  cached_network_image: ^3.2.2
  map: ^1.3.4
  intl_phone_number_input: ^0.7.1
  pin_code_fields: ^8.0.1
  flutter_easyloading: ^3.0.5
  carousel_slider: ^4.1.1
  flutter_rating_bar: ^4.0.1
  webview_flutter: ^4.0.5
  smooth_page_indicator: ^1.0.0+2
  flutter_dotenv: ^5.0.2
  cloud_firestore: ^4.3.0
  amplify_api: ^1.5.0
  amplify_flutter: ^1.5.0 
  get: ^4.6.5
  flutter_screenutil: ^5.9.0
  flutter_svg: ^2.0.8
  pretty_dio_logger: ^1.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  logger: ^2.0.2+1

dependency_overrides:
  intl: ^0.18.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  

flutter:
  uses-material-design: true

  assets:
    - assets/HeaderLogo.png
    - assets/car.png
    - assets/avater.png
    - assets/transparentCar.png
    - assets/Loading.gif
    - .env
